server:
  port: 8082
  servlet:
    context-path: /notification
email:
  third-party-uri : https://api.brevo.com
  apiKeyEmail: ${API_EMAIL_KEY}
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin #username and password are "root"
  kafka: # must install kafka with docker, can implement this configuration
    bootstrap-servers: localhost:9094 # port was be config at docker-compose.yml file, this port same with docker-compose.yml file
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest # is the strategy will reading the oldest message first, same dsa "queue"
      # this mean sent message is string to notification service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      # receives a message has datatype is string from identity sent to kafka that no need care what is identity sent to kafka => receives default is string
#      refreshable-serializer:  org.apache.kafka.common.serialization.StringDeserializer