server:
  port: 8082
  servlet:
    context-path: /notification
email:
  third-party-uri :
  apiKeyEmail:
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin